# Generated by Django 6.0.5 on 2026-05-30 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('city_zip', models.CharField(blank=True, max_length=100)),
                ('enquiry_type', models.CharField(choices=[('general', 'General Enquiry'), ('quote', 'Product Quote'), ('rental', 'Rental Enquiry'), ('insurance', 'Insurance / Medicare'), ('repair', 'Repair & Service')], default='general', max_length=20)),
                ('product_interest', models.CharField(blank=True, max_length=120)),
                ('best_call_time', models.CharField(blank=True, max_length=80)),
                ('message', models.TextField()),
                ('how_heard', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('resolved', 'Resolved')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
