# Generated by Django 5.0.6 on 2026-07-22 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='enquiry_type',
            field=models.CharField(choices=[('general', 'General Enquiry'), ('quote', 'Product Quote'), ('rental', 'Rental Enquiry'), ('insurance', 'Insurance'), ('repair', 'Repair & Service')], default='general', max_length=20),
        ),
    ]
