# Generated by Django 6.0.5 on 2026-05-30 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='(703) 494-7060', max_length=30)),
                ('email', models.EmailField(default='info@mandadmedical.com', max_length=254)),
                ('address', models.TextField(default='2103 Opitz Blvd, Woodbridge, VA 22191')),
                ('hours_weekday', models.CharField(default='9:00 AM – 6:00 PM', max_length=60)),
                ('hours_saturday', models.CharField(default='10:00 AM – 4:00 PM', max_length=60)),
                ('hours_sunday', models.CharField(default='Closed', max_length=60)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(max_length=120)),
                ('bio', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team/')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=120)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('body', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
