# Generated by Django 6.0.5 on 2026-05-30 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, help_text='Free-text fallback if product not in catalogue', max_length=200)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('address', models.TextField(blank=True)),
                ('duration', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('3month', '3+ Months')], default='monthly', max_length=20)),
                ('preferred_start', models.DateField(blank=True, null=True)),
                ('delivery_method', models.CharField(choices=[('delivery', 'Home Delivery & Setup'), ('pickup', 'Pick Up In Store')], default='delivery', max_length=20)),
                ('rate_quoted', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('notes', models.TextField(blank=True)),
                ('how_heard', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('confirmed', 'Confirmed'), ('active', 'Active Rental'), ('returned', 'Returned'), ('cancelled', 'Cancelled')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rental_enquiries', to='products.product')),
            ],
            options={
                'verbose_name': 'Rental Enquiry',
                'verbose_name_plural': 'Rental Enquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
