# Generated by Django 6.0.5 on 2026-05-30 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('address', models.TextField(blank=True)),
                ('delivery_method', models.CharField(choices=[('delivery', 'Home Delivery & Setup'), ('pickup', 'Pick Up In Store')], default='delivery', max_length=20)),
                ('best_call_time', models.CharField(blank=True, max_length=80)),
                ('insurance', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('how_heard', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('quoted', 'Quote Sent'), ('won', 'Converted to Sale'), ('lost', 'Lost')], default='new', max_length=20)),
                ('ref_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Quote Request',
                'verbose_name_plural': 'Quote Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='Snapshot of name at time of request', max_length=200)),
                ('product_sku', models.CharField(blank=True, max_length=60)),
                ('item_type', models.CharField(choices=[('purchase', 'Purchase'), ('rental', 'Rental')], default='purchase', max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('variant_info', models.CharField(blank=True, help_text='e.g. Colour: Camel Tan, Size: Medium', max_length=300)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quotes.quoterequest')),
            ],
        ),
    ]
